apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "newrelic.common.naming.fullname" . }}
  labels:
    {{- include "newrelic.common.labels" . | nindent 4 }}
rules: 
  - apiGroups:
    - ""
    resources:
    # following required for k8s_events, k8s_cluster receiver
    - events
    # following required for k8s_cluster receiver
    - namespaces
    # following required for prometheus, k8s_cluster receiver
    - nodes
    # following required for prometheus, k8s_cluster receiver
    - pods
    - pods/status
    # following required for prometheus, k8s_cluster receiver
    - services
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    # following required for hostmetrics, prometheus receiver
    - nodes/spec
    - nodes/stats
    - nodes/proxy
    # following required for hostmetrics, kubeletstats, and prometheus receiver
    - nodes/metrics
    # following required for filelog receiver
    - pods/logs
    verbs:
    - get
  # following required for prometheus receiver
  - apiGroups:
    - ""
    resources:
    - endpoints
    - replicationcontrollers
    - resourcequotas
    verbs:
    - list
    - watch
  # following required for prometheus receiver
  - apiGroups:
    - apps
    resources:
    - daemonsets
    - deployments
    - replicasets
    - statefulsets
    verbs:
    - get
    - list
    - watch
  # following required for prometheus receiver
  - apiGroups:
    - batch
    resources:
    - jobs
    - cronjobs
    verbs:
    - list
    - watch
  # following required for prometheus receiver
  - apiGroups:
    - autoscaling
    resources:
    - horizontalpodautoscalers
    verbs:
    - list
    - watch
