apiVersion: v1 
kind: ServiceAccount
metadata:
  name: {{ include "newrelic.common.serviceAccount.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "newrelic.common.labels" . | nindent 4 }}
